### ISSUE TITLE
CBZ files don't open on mac

### ISSUE THREAD

**Issue by MrNotch9** [ollm/OpenComic#116]
when I try to open a .cbz file, the application gives this error `An error occurred while trying to unzip the file. invalid signature: 0x7160500`
Edit: The error occurs on the latest version (0.2.1) and the previous versions too

**Comment by ollm** [comment]
If possible, please send me the cbz file that gives you error so I can examine it. If not, it would also be helpful if you know what program the file has been compressed with.

**Comment by MrNotch9** [comment]
One Piece v46 (2010) (Digital) (AnHeroGold-Empi...
<https://drive.google.com/file/d/1de3SuGlCZFuc6deXyFzGyWEVKvXozJh-/view?usp=drive_web>

**Comment by MrNotch9** [comment]
This was downloaded from nyaa.si (nyaa.si/view/1312261). All the .cbz files in this folder are not working. I'll try downloading other files and check

**Comment by MrNotch9** [comment]
Update: I think it's a file-size problem

**Comment by ollm** [comment]
I have tried to create the package from a virtual machine with macOS, previously I did it from Ubuntu, in the virtual machine I can open the `cbz` of `One Piece v46` both with the new package and with the previous one, so i'm not sure if this will fix it for you, the error with `sharp` has been fix when creating the package from the virtual machine machine https://github.com/ollm/OpenComic/issues/117

New package: https://github.com/ollm/OpenComic/releases/download/v0.2.1/OpenComic-0.2.1-mac-build2.7z

**Comment by ollm** [comment]
Close as fixed in [v1.0.0-beta.2](https://github.com/ollm/OpenComic/releases/tag/v1.0.0-beta.2).

### [v1.0.0-beta.2](https://github.com/ollm/OpenComic/releases/tag/v1.0.0-beta.2)
- [DMG](https://github.com/ollm/OpenComic/releases/download/v1.0.0-beta.2/OpenComic-1.0.0-beta.2.dmg)
- [DMG Arm64](https://github.com/ollm/OpenComic/releases/download/v1.0.0-beta.2/OpenComic-1.0.0-beta.2-arm64.dmg)
- [7z](https://github.com/ollm/OpenComic/releases/download/v1.0.0-beta.2/OpenComic-1.0.0-beta.2-mac.7z)
- [7z Arm64](https://github.com/ollm/OpenComic/releases/download/v1.0.0-beta.2/OpenComic-1.0.0-beta.2-arm64-mac.7z)
