### ISSUE TITLE
Error when I try to open the mac app for the first time

### ISSUE THREAD

**Issue by MrNotch9** [ollm/OpenComic#117]
version: 0.2.1
OS: macOS
```
Error: Uncaught Error: Cannot find module 'sharp'
Require stack:
- /Applications/OpenComic.app/Contents/Resources/app.asar/scripts/cache.js
- /Applications/OpenComic.app/Contents/Resources/app.asar/templates/index.html at linenumber 975:3 of file internal/modules/cjs/loader.js
```
```
Error: Cannot find module 'sharp'
Require stack:
- /Applications/OpenComic.app/Contents/Resources/app.asar/scripts/cache.js
- /Applications/OpenComic.app/Contents/Resources/app.asar/templates/index.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:972:15)
    at Function.i._resolveFilename (electron/js2c/renderer_init.js:35:917)
    at Module._load (internal/modules/cjs/loader.js:848:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at processTheImageQueue (/Applications/OpenComic.app/Contents/Resources/app.asar/scripts/cache.js:11:30)
    at /Applications/OpenComic.app/Contents/Resources/app.asar/scripts/cache.js:161:5
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
```

**Comment by Shrulik** [comment]
I had something similar happen in the v1.0.0-beta.1 version as well . Building the application from source solved it for me. I'm using an Intel Mac with Monterey.

**Comment by ollm** [comment]
I think this error is occurring because I am making the build for macOS from Ubuntu (Linux), and some native dependencies were not included in the build.

In version [v1.0.0-beta.2](https://github.com/ollm/OpenComic/releases/tag/v1.0.0-beta.2) I have built using a virtual machine with macOS and it seems that this error has disappeared, I have also added the DMG format as a new build and the build now is signed.

I haven't tested the Arm64 build so I don't know if it works correctly.

### [v1.0.0-beta.2](https://github.com/ollm/OpenComic/releases/tag/v1.0.0-beta.2)
- [DMG](https://github.com/ollm/OpenComic/releases/download/v1.0.0-beta.2/OpenComic-1.0.0-beta.2.dmg)
- [DMG Arm64](https://github.com/ollm/OpenComic/releases/download/v1.0.0-beta.2/OpenComic-1.0.0-beta.2-arm64.dmg)
- [7z](https://github.com/ollm/OpenComic/releases/download/v1.0.0-beta.2/OpenComic-1.0.0-beta.2-mac.7z)
- [7z Arm64](https://github.com/ollm/OpenComic/releases/download/v1.0.0-beta.2/OpenComic-1.0.0-beta.2-arm64-mac.7z)

**Comment by Shrulik** [comment]
Checked the DMG and can confirm it works without error.
