### ISSUE TITLE
Problem clearing Temp data

### ISSUE THREAD

**Issue by bumbaras** [ollm/OpenComic#146]
It's great app. I have read in the past that the app had an issue due to not removing own data from Temp folder. Current version tries to do that, but it only half works. App still leaves some data in Temp, and what worse, it can leave few files from unpacked folders (each created folder represents one archive which app unpacked). And when it happens then after app is opened and reader tries to open the archive again then app will only show these what were left in Temp. It won't overwrite the files in Temp and not even try to unpack the archive again thinking probably that archive is already opened. From my observation, closing app again will remove the rest of data in Temp.

**Comment by bumbaras** [comment]
I hope this project is still ongoing. I think it is one of best app among similar ones.

**Comment by ollm** [comment]
Closed as completed in c1259bb512983751fe41304c7c642966b204aea1 and available in [v1.0.0-beta.1](https://github.com/ollm/OpenComic/releases/tag/v1.0.0-beta.1)

Feel free to reopen the issue if you find any bugs.

**Comment by bumbaras** [comment]
Doesn't work with Windows 7 like the stable version. Message is can't find entry for DiscardVirtualMemory in kernel32.dll.
Need to get back to the previous version.

**Comment by ollm** [comment]
Hi, OpenComic `v1.0.0` has been updated to electron 27, since version 23 of electron, Windows 7, 8 and 8.1 have no longer been supported, [Electron Windows 7 to 8.1 deprecation notice](https://www.electronjs.org/es/blog/windows-7-to-8-1-deprecation-notice)

I have made a build with version 22 of electron that should work on Windows 7,  although it is possible that some things do not work as expected: https://mega.nz/file/7SpDGBaT#tMOvHFnkVDOuCT2Rf8u6PhNhxlu41-iNtmqok7JWJnE

To continue using the versions that are released of OpenComic, you can build from the source changing electron version in `package.json`

### First time:

**Requirements**: Git, Node and NPM

``` bash
git clone https://github.com/ollm/OpenComic.git
cd OpenComic
npm install
npm run rebuild
```

### Build from master version:

```
npm pull origin master
```
Change the electron version in `package.json` to `22.3.23` (In `devDependencies`)
```
npm install
npm run build-nsis
```

The `exe` file is located in `dist` folder.

**Comment by bumbaras** [comment]
Downloaded, thank You.
