### ISSUE TITLE
Android version required

### ISSUE THREAD

**Issue by CaptMacTavish** [ollm/OpenComic#156]
An Android version release must be preferable for this software.

**Comment by aorin1** [comment]
It will surely be appreciated to have OpenComic available on Android!

**Comment by ollm** [comment]
Electron does not currently [support](https://github.com/electron/electron/issues/562) Android/iOS, to be able to do this many parts of OpenComic would have to be rewritten so that it at least worked on cordova/capacitor, and this would take a lot of work.

Another option would be if OpenComic could create a server that could be accessed from a simple browser or application, something similar to [Tachidesk Server](https://github.com/Suwayomi/Tachidesk-Server), but this would also take a lot of work.

I'm closing this for now, as I don't plan to do so.
