### ISSUE TITLE
Viewport stuck on loading animation when a panel is opened

### ISSUE THREAD

**Issue by mojo-jojo-7** [ollm/OpenComic#160]
Version: `v1.0.0-beta.1`

Tested with the default "Pepper & Carrot" comic as well. Doesn't work. The viewport just shows the loading animation ad infinitum. It was working fine in `v0.2.1`

**Comment by ollm** [comment]
Are there any errors in DevTools Console? (Debug > Toggle DevTools > Console)

What display preferences do you use in reading mode?

**Comment by ollm** [comment]
OpenComic data is backwards compatible, looking at the error message it seems that it fails when trying to find the next comic that it will have to jump to once it reaches the end of the reading.

This part of the code was rewritten for `v1.0.0`  c1259bb512983751fe41304c7c642966b204aea1 to fix multiple bugs and performance issues, though these changes may have added new bugs.

For now, I close the issue, since it seems that it has already been solved, if the error appears again, comment this issue and I will reopen again.
