### ISSUE TITLE
[Feature Request]: Delete chapter after reading

### ISSUE THREAD

**Issue by Cikapkamuy** [ollm/OpenComic#181]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/ollm/OpenComic/issues) for a feature request that matches the one I want to file, without success.

### Describe your suggested feature

Having the option to automatically delete a chapter after reading or at least move it to the recycle bin.

**Comment by ollm** [comment]
I don't think I implement this, since the way OpenComic works this could be potentially dangerous, if a user added a folder incorrectly, important files could be deleted for them without them realizing, I think it is better for the user to delete chapters manually, using the file manager, you can use the "Open file location" option to speed this up.
