### ISSUE TITLE
Are the images extracted from the CBR o CBZ?

### ISSUE THREAD

**Issue by vivadavid** [ollm/OpenComic#198]
Hi,

I have recently found out that MComix extracts the images contained in a CBR or CBZ in order to view the pages of the comic and I was wondering if OpenComic does the same thing. I thought images inside a ZIP or a RAR file could be viewed without having to extract anything, but maybe I misunderstood this and it's inevitable.

My main concern is to avoid unnecessary writing on the SSD of my laptop.

Thanks in advance for the information.

**Comment by ollm** [comment]
Hi.

OpenComic also extracts images from cbr, cbz, etc to a temporary folder as needed, this extraction is only done once if you have "Maximum temporary files" configured (4GB by default), so if you open the same file again it will not be extracted and will be read from the temporary folder if it is still there over there (Oldest files are deleted from the temporary folder when the maximum size is reached)

> I thought images inside a ZIP or a RAR file could be viewed without having to extract anything

zip, rar, etc can extract files to memory instead of disk, but this is complicated to implement and there are some OpenComic functions that depend currently on extracting the images/files, such as generating thumbnails.

![Captura desde 2024-02-09 14-21-59](https://github.com/ollm/OpenComic/assets/18549191/c09bdfcc-8e1b-406a-8e52-3af0c6080dc9)

**Comment by vivadavid** [comment]
Thank you for the quick reply, @ollm !
