### ISSUE TITLE
[Bug]: Long delay when backing out of comic to large library/bookshelf

### ISSUE THREAD

**Issue by wheresmytyphone** [ollm/OpenComic#227]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/ollm/OpenComic/issues) for a bug report that matches the one I want to file, without success.

### OpenComic Version

1.2.1 (windows store)

### Operating System

Windows 11 26200 (24H2)

### Steps to reproduce

1.Open application, library loads and generates thumbnails
2. After opening a comic, click the arrow or press escape to return to main library.
3. There is a very long delay between pressing back and actually returning to main library, it seems to be about the same amount of time as the initial load when opening the app.

### Expected Behavior

To return to library with little delay

### Actual Behavior

Applicstion stays on comic page for about 22-25 seconds before returning to main library page

### Additional Information

library is about 1100 CBZ/zip files, all in single folder, stored on an external SSD that other comic library applications access without this delay.

**Comment by ollm** [comment]
It seems that it is because OpenComic shows the entire library/folders at once, probably slows down when find for thumbnails, this has to be done every time, when opening the app for the first time, when reloading or going back and forth, etc.

I'm going to make some changes so that it only shows and find for the thumbnails of the files that only appear on the screen, and as you scroll the rest.

Even so, it would help if you did a performance test to see if there is anything specifically slowing down the loading.

These are the steps to do it, I also leave you an example video:

`Debug `> `Toogle DevTools` > `Performance `> `Start and Reload Page Button` > `Wait for the page to finish loading` > `Stop` > `Save profile`

https://github.com/ollm/OpenComic/assets/18549191/f6b18079-7dcd-413e-bfbb-9d2224fa9465

Once you have saved the `.json` file you can upload it here for analysis.
