### ISSUE TITLE
[Bug]: OpenComic Unresponsive

### ISSUE THREAD

**Issue by jjoshw** [ollm/OpenComic#228]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/ollm/OpenComic/issues) for a bug report that matches the one I want to file, without success.

### OpenComic Version

1.2.0

### Operating System

macOS Mojave 10.14.6

### Steps to reproduce

Just installed and have a red window. None of the Menu options appear to do anything. Can't even quit :(
First downloaded it from GitHub and when it didn't work I uninstalled it and bought it on the App Store. Same lack of functionality I'm afraid

### Expected Behavior

Ability to read a comic

### Actual Behavior

Unresponsive menus - nothing happens

### Error message

None

**Comment by ollm** [comment]
It seems there are two issues here.

The first is probably the same as https://github.com/ollm/OpenComic/issues/224#issuecomment-2090465996, the version of `sharp` that OpenComic uses in the GitHub version and the App Store version has a bug in macOS 10.15 or lower, this is currently fixed in the master branch and will be in the next release 153902cba8d8d8592919bc234e1cef52a00f4f5b

The second is that the version of `electron` that OpenComic uses no longer supports macOS 10.14 or lower https://www.electronjs.org/blog/electron-27-0#removed-macos-1013--1014-support I have added the minimum supported version of macOS 9ba9c1eef1645e3f416518872aecd68c83c57079

I have made a special build with the latest compatible version of `electron` with macOS 10.14 (`version 26`) and the updated `sharp` version, this should work for you without the issue.

Build: https://mega.nz/file/fDwEgQ7I#i9zAxGAUHuwe_EYK7fkvQMFSOHMxpnqs8SNdMCk6j_I

**Comment by jjoshw** [comment]
Hi Oleguer,

Thanks so much for your help! It works beautifully now :)
Thank you for your kind support.

Cheers,
Jeremy
