### ISSUE TITLE
Next volume link auto detection for Comic view

### ISSUE THREAD

**Issue by yasuflatland-lf** [ollm/OpenComic#42]
The next volume link at, or after the end of the page as a hover, is convenient when you read series of comics (Say volume1, volume2 ...)

The series of comics usually have the same prefix, say "Comic. Foobar vol1", "Comic Foobar vol2". So if the same comic name prefix is detected in registered folders or files in OpenComic, a link to the next volume is displayed, maybe hover the link on the last page or a blank page after the last page with the link.

**Comment by ollm** [comment]
This is already implemented in OpenComic, although it works differently than mentioned, for example instead of adding each volume to OpenComic, you have to add the parent folder where all the volumes of the comic are, in this way when you reach the end of the volume you will jump to the next one.

Like this:
```
-↴ Comic folder
 - Volume 1
 - Volume 2
 - ...
```
You have to add the "Comic folder" instead of the volumes to OpenComic.
