### ISSUE TITLE
Not generating preview pictures consistently.

### ISSUE THREAD

**Issue by EliCodesForFun** [ollm/OpenComic#51]
![OpenComic_B80AmTVnud](https://user-images.githubusercontent.com/9376306/90801242-a7451f00-e2e3-11ea-9c92-4e0ac7c77705.png)

The images are contained within a subfolder within the zip, if this helps diagnose. This is very common for comics. Pics attached.
![WinRAR_ubYYR9skoR](https://user-images.githubusercontent.com/9376306/90801395-d65b9080-e2e3-11ea-8ceb-ca70896b4983.png)
![WinRAR_f4SyFAK8Ro](https://user-images.githubusercontent.com/9376306/90801402-d8bdea80-e2e3-11ea-9f20-1ecf94032da5.png)

Almost all my zipped comics are like this, but the behavior in the app is inconsistent. After I open the zip, I do get the preview image, but it's very small as you can see.

I think the issue might have to do with the size of the first .jpg or .png in the folder, or its total size. It seems to be that any zip file over 50MB won't preview.

**Comment by ollm** [comment]
The decompression of files when making thumbnails is limited to 50 MB, this is due to the fact that the App does not currently delete the decompressed files after making the thumbnails, the files are kept in the tmp folder until the PC is restarted / shut down, I will add soon an option to increase this limit and I will make the unzipped files delete after generating the thumbnail.

https://github.com/ollm/OpenComic/blob/0bbdcfd25bea692b4958c05ae28006503bc179e6/scripts/dom.js#L670

The problem with the small thumbnail is because currently 4 images are displayed, as there is only one, the others appear in white, I will have to add an option so that it can be configured in large (1 Image) or in small (4 Images).

![Screenshot](https://user-images.githubusercontent.com/18549191/90806856-e55f3480-e31d-11ea-9b0d-970c621ac3cd.jpg)

**Comment by vladz0r** [comment]
> The decompression of files when making thumbnails is limited to 50 MB, this is due to the fact that the App does not currently delete the decompressed files after making the thumbnails, the files are kept in the tmp folder until the PC is restarted / shut down, I will add soon an option to increase this limit and I will make the unzipped files delete after generating the thumbnail.
> 
> 
> The problem with the small thumbnail is because currently 4 images are displayed, as there is only one, the others appear in white, I will have to add an option so that it can be configured in large (1 Image) or in small (4 Images).
> 

If you fix these two things you're like my hero.
Some hotkeys could be pretty cool too, like for going to the next or previous folder, but I like the interface.
It would also be very ideal if your "scroll down" through your library could be saved (persist) when hitting Back from viewing a comic zip file, so that you could more easily go from 1 zip file to the next. Currently you'd have to scroll all the way back down. Some people might have large collections of zipped art they're checking through (like me).

**Comment by ollm** [comment]
Closed as completed in c1259bb512983751fe41304c7c642966b204aea1 and available in [v1.0.0-beta.1](https://github.com/ollm/OpenComic/releases/tag/v1.0.0-beta.1)

Feel free to reopen the issue if you find any bugs.
