### ISSUE TITLE
ctrl/cmd+0 to reset zoom quickly.

### ISSUE THREAD

**Issue by frykauf** [ollm/OpenComic#78]
Especially useful if you accidentally pinch to zoom.

**Comment by ollm** [comment]
Closed as completed in 0a4a4597883c7c6c837acdd61e4d80dc8c0a0ec1 due to implementation of custom keyboard shortcuts and available in [v1.0.0-beta.2](https://github.com/ollm/OpenComic/releases/tag/v1.0.0-beta.2)

If you are missing any default shortcuts or any configurable action, open a new issue and I will try to add it for the next version.
